# Generated by Django 4.0.3 on 2022-03-29 07:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favpics', '0002_location_image_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='images',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
